package M4;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes3.dex */
public abstract class m1 {
    public static final l1 A0;
    public static final l1 B0;
    public static final l1 C0;
    public static final l1 D0;
    public static final l1 E0;
    public static final l1 F0;
    public static final l1 G0;
    public static final l1 H0;
    public static final l1 I0;
    public static final l1 J0;
    public static final l1 K0;
    public static final l1 M;
    public static final l1 N;
    public static final l1 O;
    public static final l1 P;
    public static final l1 Q;
    public static final l1 R;
    public static final l1 S;
    public static final l1 T;
    public static final l1 U;
    public static final l1 V;
    public static final l1 W;
    public static final l1 X;
    public static final l1 Y;
    public static final l1 Z;
    public static final l1 a0;
    public static final l1 b0;
    public static final l1 c0;
    public static final l1 d0;
    public static final l1 e0;
    public static final l1 f0;
    public static final l1 g0;
    public static final l1 h0;
    public static final l1 i0;
    public static final l1 j0;
    public static final l1 k0;
    public static final l1 l0;
    public static final l1 m0;
    public static final l1 n0;
    public static final l1 o0;
    public static final l1 p0;
    public static final l1 q0;
    public static final l1 r0;
    public static final l1 s0;
    public static final l1 t0;
    public static final l1 u0;
    public static final l1 v0;
    public static final l1 w0;
    public static final l1 x0;
    public static final l1 y0;
    public static final l1 z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final Set b = Collections.synchronizedSet(new HashSet());
    public static final l1 c = a("measurement.ad_id_cache_time", 10000L, 10000L, J.a);
    public static final l1 d = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, 3600000L, A.a);
    public static final l1 e = a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, N.a);
    public static final l1 f = a("measurement.config.cache_time", 86400000L, 3600000L, a0.a);
    public static final l1 g = a("measurement.config.url_scheme", "https", "https", n0.a);
    public static final l1 h = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", z0.a);
    public static final l1 i = a("measurement.upload.max_bundles", 100, 100, M0.a);
    public static final l1 j = a("measurement.upload.max_batch_size", 65536, 65536, Y0.a);
    public static final l1 k = a("measurement.upload.max_bundle_size", 65536, 65536, d1.a);
    public static final l1 l = a("measurement.upload.max_events_per_bundle", 1000, 1000, e1.a);
    public static final l1 m = a("measurement.upload.max_events_per_day", 100000, 100000, V.a);
    public static final l1 n = a("measurement.upload.max_error_events_per_day", 1000, 1000, h0.a);
    public static final l1 o = a("measurement.upload.max_public_events_per_day", 50000, 50000, s0.a);
    public static final l1 p = a("measurement.upload.max_conversions_per_day", 10000, 10000, D0.a);
    public static final l1 q = a("measurement.upload.max_realtime_events_per_day", 10, 10, P0.a);
    public static final l1 r = a("measurement.store.max_stored_events_per_app", 100000, 100000, a1.a);
    public static final l1 s = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", g1.a);
    public static final l1 t = a("measurement.upload.backoff_period", 43200000L, 43200000L, h1.a);
    public static final l1 u = a("measurement.upload.window_interval", 3600000L, 3600000L, y.a);
    public static final l1 v = a("measurement.upload.interval", 3600000L, 3600000L, z.a);
    public static final l1 w = a("measurement.upload.realtime_upload_interval", 10000L, 10000L, C.a);
    public static final l1 x = a("measurement.upload.debug_upload_interval", 1000L, 1000L, D.a);
    public static final l1 y = a("measurement.upload.minimum_delay", 500L, 500L, E.a);
    public static final l1 z = a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, F.a);
    public static final l1 A = a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, G.a);
    public static final l1 B = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, H.a);
    public static final l1 C = a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, I.a);
    public static final l1 D = a("measurement.upload.retry_time", 1800000L, 1800000L, K.a);
    public static final l1 E = a("measurement.upload.retry_count", 6, 6, L.a);
    public static final l1 F = a("measurement.upload.max_queue_time", 2419200000L, 2419200000L, M.a);
    public static final l1 G = a("measurement.lifetimevalue.max_currency_tracked", 4, 4, O.a);
    public static final l1 H = a("measurement.audience.filter_result_max_count", 200, 200, P.a);
    public static final l1 I = a("measurement.upload.max_public_user_properties", 25, 25, null);
    public static final l1 J = a("measurement.upload.max_event_name_cardinality", 500, 500, null);
    public static final l1 K = a("measurement.upload.max_public_event_params", 25, 25, null);
    public static final l1 L = a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, Q.a);

    static {
        Boolean bool = Boolean.FALSE;
        M = a("measurement.test.boolean_flag", bool, bool, S.a);
        N = a("measurement.test.string_flag", "---", "---", T.a);
        O = a("measurement.test.long_flag", -1L, -1L, U.a);
        P = a("measurement.test.int_flag", -2, -2, W.a);
        Double valueOf = Double.valueOf(-3.0d);
        Q = a("measurement.test.double_flag", valueOf, valueOf, X.a);
        R = a("measurement.experiment.max_ids", 50, 50, Y.a);
        S = a("measurement.upload.max_item_scoped_custom_parameters", 27, 27, Z.a);
        T = a("measurement.max_bundles_per_iteration", 100, 100, b0.a);
        U = a("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, c0.a);
        V = a("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, e0.a);
        Boolean bool2 = Boolean.TRUE;
        W = a("measurement.collection.log_event_and_bundle_v2", bool2, bool2, f0.a);
        X = a("measurement.quality.checksum", bool, bool, null);
        Y = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, g0.a);
        Z = a("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, i0.a);
        a0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, j0.a);
        b0 = a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, k0.a);
        c0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, l0.a);
        d0 = a("measurement.lifecycle.app_in_background_parameter", bool, bool, m0.a);
        e0 = a("measurement.integration.disable_firebase_instance_id", bool, bool, o0.a);
        f0 = a("measurement.collection.service.update_with_analytics_fix", bool, bool, p0.a);
        g0 = a("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, q0.a);
        h0 = a("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, r0.a);
        i0 = a("measurement.collection.synthetic_data_mitigation", bool, bool, t0.a);
        j0 = a("measurement.service.storage_consent_support_version", 203600, 203600, u0.a);
        k0 = a("measurement.client.click_identifier_control.dev", bool, bool, v0.a);
        l0 = a("measurement.service.click_identifier_control", bool, bool, w0.a);
        m0 = a("measurement.service.store_null_safelist", bool2, bool2, x0.a);
        n0 = a("measurement.service.store_safelist", bool2, bool2, y0.a);
        o0 = a("measurement.collection.enable_session_stitching_token.first_open_fix", bool2, bool2, A0.a);
        p0 = a("measurement.collection.enable_session_stitching_token.client.dev", bool2, bool2, B0.a);
        q0 = a("measurement.session_stitching_token_enabled", bool, bool, C0.a);
        r0 = a("measurement.sgtm.client.dev", bool, bool, F0.a);
        s0 = a("measurement.sgtm.service", bool, bool, G0.a);
        t0 = a("measurement.redaction.retain_major_os_version", bool2, bool2, H0.a);
        u0 = a("measurement.redaction.scion_payload_generator", bool2, bool2, I0.a);
        v0 = a("measurement.service.clear_global_params_on_uninstall", bool2, bool2, J0.a);
        w0 = a("measurement.sessionid.enable_client_session_id", bool2, bool2, K0.a);
        x0 = a("measurement.sfmc.client", bool2, bool2, L0.a);
        y0 = a("measurement.sfmc.service", bool2, bool2, N0.a);
        z0 = a("measurement.gmscore_feature_tracking", bool2, bool2, O0.a);
        A0 = a("measurement.fix_health_monitor_stack_trace", bool2, bool2, Q0.a);
        B0 = a("measurement.item_scoped_custom_parameters.client", bool2, bool2, R0.a);
        C0 = a("measurement.item_scoped_custom_parameters.service", bool, bool, S0.a);
        D0 = a("measurement.remove_app_background.client", bool, bool, T0.a);
        E0 = a("measurement.rb.attribution.service", bool, bool, U0.a);
        F0 = a("measurement.collection.client.log_target_api_version", bool2, bool2, V0.a);
        G0 = a("measurement.collection.service.log_target_api_version", bool2, bool2, W0.a);
        H0 = a("measurement.client.deep_link_referrer_fix", bool2, bool2, X0.a);
        I0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, bool, Z0.a);
        J0 = a("measurement.link_sst_to_sid", bool2, bool2, b1.a);
        K0 = a("measurement.client.ad_id_consent_fix", bool2, bool2, c1.a);
    }

    public static l1 a(String str, Object obj, Object obj2, i1 i1Var) {
        l1 l1Var = new l1(str, obj, obj2, i1Var, null);
        a.add(l1Var);
        return l1Var;
    }

    public static /* bridge */ /* synthetic */ List b() {
        return a;
    }
}
