package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes.dex */
class RegionDefaults {
    public static List getRegions() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        updateRegion(region, "autoscaling", "autoscaling.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "dynamodb", "dynamodb.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "ec2", "ec2.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "elasticloadbalancing", "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "sns", "sns.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "sqs", "sqs.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "sts", "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        updateRegion(region2, "autoscaling", "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "dynamodb", "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "ec2", "ec2.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "sdb", "sdb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "sns", "sns.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "sqs", "sqs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "sts", "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        updateRegion(region3, "autoscaling", "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "cognito-identity", "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "cognito-idp", "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "cognito-sync", "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "dynamodb", "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "ec2", "ec2.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "elasticloadbalancing", "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "iot", "iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "logs", "logs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "s3", "s3.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "sns", "sns.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "sqs", "sqs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "sts", "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList.add(region4);
        updateRegion(region4, "autoscaling", "autoscaling.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-identity", "cognito-identity.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-idp", "cognito-idp.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "cognito-sync", "cognito-sync.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "dynamodb", "dynamodb.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "ec2", "ec2.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "elasticloadbalancing", "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "logs", "logs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "polly", "polly.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "s3", "s3.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "sns", "sns.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "sqs", "sqs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "sts", "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", "amazonaws.com");
        arrayList.add(region5);
        updateRegion(region5, "autoscaling", "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "cognito-identity", "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "cognito-idp", "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "cognito-sync", "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "data.iot", "data.iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "dynamodb", "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "ec2", "ec2.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "iot", "iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "logs", "logs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "polly", "polly.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "s3", "s3.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "sdb", "sdb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "sns", "sns.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "sqs", "sqs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "sts", "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", "amazonaws.com");
        arrayList.add(region6);
        updateRegion(region6, "autoscaling", "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "cognito-identity", "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "cognito-idp", "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "cognito-sync", "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "data.iot", "data.iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "dynamodb", "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "ec2", "ec2.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "iot", "iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "lambda", "lambda.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "logs", "logs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "polly", "polly.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "s3", "s3.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "sdb", "sdb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "sns", "sns.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "sqs", "sqs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "sts", "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", "amazonaws.com");
        arrayList.add(region7);
        updateRegion(region7, "autoscaling", "autoscaling.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "dynamodb", "dynamodb.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "ec2", "ec2.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "elasticloadbalancing", "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "lambda", "lambda.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "logs", "logs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "polly", "polly.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "s3", "s3.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "sns", "sns.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "sqs", "sqs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "sts", "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", "amazonaws.com");
        arrayList.add(region8);
        updateRegion(region8, "autoscaling", "autoscaling.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-identity", "cognito-identity.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-idp", "cognito-idp.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "cognito-sync", "cognito-sync.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "data.iot", "data.iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "dynamodb", "dynamodb.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "ec2", "ec2.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "elasticloadbalancing", "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "firehose", "firehose.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "iot", "iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "lambda", "lambda.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "logs", "logs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "polly", "polly.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "s3", "s3.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "sns", "sns.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "sqs", "sqs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "sts", "sts.eu-central-1.amazonaws.com", false, true);
        Region region9 = new Region("eu-central-2", "amazonaws.com");
        arrayList.add(region9);
        updateRegion(region9, "autoscaling", "autoscaling.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "cognito-identity", "cognito-identity.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "cognito-idp", "cognito-idp.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "cognito-sync", "cognito-sync.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "data.iot", "data.iot.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "dynamodb", "dynamodb.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "ec2", "ec2.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "elasticloadbalancing", "elasticloadbalancing.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "firehose", "firehose.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "iot", "iot.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "kinesis", "kinesis.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "kms", "kms.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "lambda", "lambda.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "logs", "logs.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "polly", "polly.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "s3", "s3.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "sdb", "sdb.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "sns", "sns.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "sqs", "sqs.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "sts", "sts.eu-central-2.amazonaws.com", false, true);
        Region region10 = new Region("eu-south-1", "amazonaws.com");
        arrayList.add(region10);
        updateRegion(region10, "autoscaling", "autoscaling.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "dynamodb", "dynamodb.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "ec2", "ec2.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "elasticloadbalancing", "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "lambda", "lambda.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "logs", "logs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "s3", "s3.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "sns", "sns.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "sqs", "sqs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, "sts", "sts.eu-south-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-south-2", "amazonaws.com");
        arrayList.add(region11);
        updateRegion(region11, "autoscaling", "autoscaling.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "cognito-identity", "cognito-identity.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "cognito-idp", "cognito-idp.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "cognito-sync", "cognito-sync.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "data.iot", "data.iot.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "dynamodb", "dynamodb.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "ec2", "ec2.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "elasticloadbalancing", "elasticloadbalancing.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "firehose", "firehose.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "iot", "iot.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "kinesis", "kinesis.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "kms", "kms.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "lambda", "lambda.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "logs", "logs.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "polly", "polly.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "s3", "s3.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "sdb", "sdb.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "sns", "sns.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "sqs", "sqs.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, "sts", "sts.eu-south-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-1", "amazonaws.com");
        arrayList.add(region12);
        updateRegion(region12, "autoscaling", "autoscaling.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "cognito-idp", "cognito-idp.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "data.iot", "data.iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "dynamodb", "dynamodb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "ec2", "ec2.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "elasticloadbalancing", "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "iot", "iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "logs", "logs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "polly", "polly.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "s3", "s3.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "sdb", "sdb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "sns", "sns.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "sqs", "sqs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "sts", "sts.eu-west-1.amazonaws.com", false, true);
        Region region13 = new Region("eu-west-2", "amazonaws.com");
        arrayList.add(region13);
        updateRegion(region13, "autoscaling", "autoscaling.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "cognito-identity", "cognito-identity.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "cognito-idp", "cognito-idp.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "cognito-sync", "cognito-sync.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "dynamodb", "dynamodb.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "ec2", "ec2.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "elasticloadbalancing", "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "iot", "iot.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "kinesis", "kinesis.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "kms", "kms.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "lambda", "lambda.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "logs", "logs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "polly", "polly.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "s3", "s3.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "sns", "sns.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "sqs", "sqs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, "sts", "sts.eu-west-2.amazonaws.com", false, true);
        Region region14 = new Region("eu-west-3", "amazonaws.com");
        arrayList.add(region14);
        updateRegion(region14, "autoscaling", "autoscaling.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "dynamodb", "dynamodb.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "ec2", "ec2.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "elasticloadbalancing", "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "kinesis", "kinesis.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "kms", "kms.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "lambda", "lambda.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "logs", "logs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "polly", "polly.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "s3", "s3.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "sns", "sns.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "sqs", "sqs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, "sts", "sts.eu-west-3.amazonaws.com", false, true);
        Region region15 = new Region("sa-east-1", "amazonaws.com");
        arrayList.add(region15);
        updateRegion(region15, "autoscaling", "autoscaling.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "dynamodb", "dynamodb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "ec2", "ec2.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "elasticloadbalancing", "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "kinesis", "kinesis.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "lambda", "lambda.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "logs", "logs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "polly", "polly.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "s3", "s3.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "sdb", "sdb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "sns", "sns.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "sqs", "sqs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, "sts", "sts.sa-east-1.amazonaws.com", false, true);
        Region region16 = new Region("us-east-1", "amazonaws.com");
        arrayList.add(region16);
        updateRegion(region16, "autoscaling", "autoscaling.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "data.iot", "data.iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "dynamodb", "dynamodb.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "ec2", "ec2.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "elasticloadbalancing", "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "iot", "iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "kms", "kms.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "logs", "logs.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "polly", "polly.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "s3", "s3.amazonaws.com", false, true);
        updateRegion(region16, "sdb", "sdb.amazonaws.com", false, true);
        updateRegion(region16, "sns", "sns.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "sqs", "sqs.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "sts", "sts.us-east-1.amazonaws.com", false, true);
        Region region17 = new Region("us-east-2", "amazonaws.com");
        arrayList.add(region17);
        updateRegion(region17, "autoscaling", "autoscaling.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "cognito-identity", "cognito-identity.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "cognito-idp", "cognito-idp.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "cognito-sync", "cognito-sync.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "dynamodb", "dynamodb.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "ec2", "ec2.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "elasticloadbalancing", "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "firehose", "firehose.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "iot", "iot.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "kinesis", "kinesis.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "kms", "kms.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "lambda", "lambda.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "logs", "logs.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "polly", "polly.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "s3", "s3.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "sns", "sns.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "sqs", "sqs.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, "sts", "sts.us-east-2.amazonaws.com", false, true);
        Region region18 = new Region("us-west-1", "amazonaws.com");
        arrayList.add(region18);
        updateRegion(region18, "autoscaling", "autoscaling.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "dynamodb", "dynamodb.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "ec2", "ec2.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "elasticloadbalancing", "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "kms", "kms.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "lambda", "lambda.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "logs", "logs.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "polly", "polly.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "s3", "s3.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "sdb", "sdb.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "sns", "sns.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "sqs", "sqs.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, "sts", "sts.us-west-1.amazonaws.com", false, true);
        Region region19 = new Region("us-west-2", "amazonaws.com");
        arrayList.add(region19);
        updateRegion(region19, "autoscaling", "autoscaling.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "cognito-identity", "cognito-identity.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "cognito-idp", "cognito-idp.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "cognito-sync", "cognito-sync.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "data.iot", "data.iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "dynamodb", "dynamodb.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "ec2", "ec2.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "elasticloadbalancing", "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "iot", "iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "kms", "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "logs", "logs.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "polly", "polly.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "s3", "s3.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "sdb", "sdb.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "sns", "sns.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "sqs", "sqs.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "sts", "sts.us-west-2.amazonaws.com", false, true);
        Region region20 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList.add(region20);
        updateRegion(region20, "autoscaling", "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "cognito-identity", "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "dynamodb", "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "ec2", "ec2.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "elasticloadbalancing", "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "iot", "iot.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "kinesis", "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "lambda", "lambda.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "logs", "logs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "s3", "s3.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "sns", "sns.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "sqs", "sqs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, "sts", "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region21 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList.add(region21);
        updateRegion(region21, "autoscaling", "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "dynamodb", "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "ec2", "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "elasticloadbalancing", "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "kinesis", "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "logs", "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "s3", "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "sns", "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "sqs", "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, "sts", "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        Region region22 = new Region("us-gov-west-1", "amazonaws.com");
        arrayList.add(region22);
        updateRegion(region22, "autoscaling", "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "dynamodb", "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "ec2", "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "elasticloadbalancing", "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "kinesis", "kinesis.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "kms", "kms.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "lambda", "lambda.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "logs", "logs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "s3", "s3.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "sns", "sns.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "sqs", "sqs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, "sts", "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region23 = new Region("eu-north-1", "amazonaws.com");
        arrayList.add(region23);
        updateRegion(region23, "autoscaling", "autoscaling.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "dynamodb", "dynamodb.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "ec2", "ec2.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "elasticloadbalancing", "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "firehose", "firehose.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "iot", "iot.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "kinesis", "kinesis.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "kms", "kms.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "lambda", "lambda.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "logs", "logs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "s3", "s3.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "sns", "sns.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "sqs", "sqs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region23, "sts", "sts.eu-north-1.amazonaws.com", false, true);
        Region region24 = new Region("ap-east-1", "amazonaws.com");
        arrayList.add(region24);
        updateRegion(region24, "autoscaling", "autoscaling.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "dynamodb", "dynamodb.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "ec2", "ec2.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "elasticloadbalancing", "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "firehose", "firehose.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "kinesis", "kinesis.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "kms", "kms.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "lambda", "lambda.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "logs", "logs.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "polly", "polly.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "s3", "s3.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "sns", "sns.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "sqs", "sqs.ap-east-1.amazonaws.com", false, true);
        updateRegion(region24, "sts", "sts.ap-east-1.amazonaws.com", false, true);
        Region region25 = new Region("me-south-1", "amazonaws.com");
        arrayList.add(region25);
        updateRegion(region25, "autoscaling", "autoscaling.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "cognito-identity", "cognito-identity.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "cognito-idp", "cognito-idp.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "cognito-sync", "cognito-sync.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "data.iot", "data.iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "dynamodb", "dynamodb.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "ec2", "ec2.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "elasticloadbalancing", "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "firehose", "firehose.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "iot", "iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "kinesis", "kinesis.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "kms", "kms.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "lambda", "lambda.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "logs", "logs.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "polly", "polly.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "s3", "s3.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "sdb", "sdb.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "sns", "sns.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "sqs", "sqs.me-south-1.amazonaws.com", false, true);
        updateRegion(region25, "sts", "sts.me-south-1.amazonaws.com", false, true);
        Region region26 = new Region("ap-southeast-3", "amazonaws.com");
        arrayList.add(region26);
        updateRegion(region26, "autoscaling", "autoscaling.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "cognito-identity", "cognito-identity.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "cognito-idp", "cognito-idp.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "cognito-sync", "cognito-sync.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "data.iot", "data.iot.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "dynamodb", "dynamodb.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "ec2", "ec2.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "elasticloadbalancing", "elasticloadbalancing.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "firehose", "firehose.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "iot", "iot.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "kinesis", "kinesis.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "kms", "kms.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "lambda", "lambda.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "logs", "logs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "polly", "polly.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "s3", "s3.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "sdb", "sdb.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "sns", "sns.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "sqs", "sqs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region26, "sts", "sts.ap-southeast-3.amazonaws.com", false, true);
        Region region27 = new Region("me-central-1", "amazonaws.com");
        arrayList.add(region27);
        updateRegion(region27, "autoscaling", "autoscaling.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "cognito-identity", "cognito-identity.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "cognito-idp", "cognito-idp.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "cognito-sync", "cognito-sync.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "data.iot", "data.iot.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "dynamodb", "dynamodb.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "ec2", "ec2.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "elasticloadbalancing", "elasticloadbalancing.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "firehose", "firehose.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "iot", "iot.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "kinesis", "kinesis.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "kms", "kms.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "lambda", "lambda.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "logs", "logs.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "polly", "polly.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "s3", "s3.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "sdb", "sdb.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "sns", "sns.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "sqs", "sqs.me-central-1.amazonaws.com", false, true);
        updateRegion(region27, "sts", "sts.me-central-1.amazonaws.com", false, true);
        Region region28 = new Region("ap-south-2", "amazonaws.com");
        arrayList.add(region28);
        updateRegion(region28, "autoscaling", "autoscaling.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "cognito-identity", "cognito-identity.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "cognito-idp", "cognito-idp.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "cognito-sync", "cognito-sync.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "data.iot", "data.iot.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "dynamodb", "dynamodb.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "ec2", "ec2.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "elasticloadbalancing", "elasticloadbalancing.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "firehose", "firehose.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "iot", "iot.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "kinesis", "kinesis.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "kms", "kms.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "lambda", "lambda.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "logs", "logs.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "polly", "polly.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "s3", "s3.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "sdb", "sdb.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "sns", "sns.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "sqs", "sqs.ap-south-2.amazonaws.com", false, true);
        updateRegion(region28, "sts", "sts.ap-south-2.amazonaws.com", false, true);
        return arrayList;
    }

    private static void updateRegion(Region region, String str, String str2, boolean z, boolean z2) {
        Map serviceEndpoints = region.getServiceEndpoints();
        Map httpSupport = region.getHttpSupport();
        Map httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(str, str2);
        httpSupport.put(str, Boolean.valueOf(z));
        httpsSupport.put(str, Boolean.valueOf(z2));
    }
}
