package com.android.billingclient.api;

import com.android.billingclient.api.a;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes.dex */
public abstract class b {
    public static final a A;
    public static final a B;
    public static final a C;
    public static final a D;
    public static final a E;
    public static final a F;
    public static final a a;
    public static final a b;
    public static final a c;
    public static final a d;
    public static final a e;
    public static final a f;
    public static final a g;
    public static final a h;
    public static final a i;
    public static final a j;
    public static final a k;
    public static final a l;
    public static final a m;
    public static final a n;
    public static final a o;
    public static final a p;
    public static final a q;
    public static final a r;
    public static final a s;
    public static final a t;
    public static final a u;
    public static final a v;
    public static final a w;
    public static final a x;
    public static final a y;
    public static final a z;

    static {
        a.a c2 = a.c();
        c2.c(3);
        c2.b("Google Play In-app Billing API version is less than 3");
        a = c2.a();
        a.a c3 = a.c();
        c3.c(3);
        c3.b("Google Play In-app Billing API version is less than 9");
        b = c3.a();
        a.a c4 = a.c();
        c4.c(3);
        c4.b("Billing service unavailable on device.");
        c = c4.a();
        a.a c5 = a.c();
        c5.c(5);
        c5.b("Client is already in the process of connecting to billing service.");
        d = c5.a();
        a.a c6 = a.c();
        c6.c(5);
        c6.b("The list of SKUs can't be empty.");
        e = c6.a();
        a.a c7 = a.c();
        c7.c(5);
        c7.b("SKU type can't be empty.");
        f = c7.a();
        a.a c8 = a.c();
        c8.c(5);
        c8.b("Product type can't be empty.");
        g = c8.a();
        a.a c9 = a.c();
        c9.c(-2);
        c9.b("Client does not support extra params.");
        h = c9.a();
        a.a c10 = a.c();
        c10.c(5);
        c10.b("Invalid purchase token.");
        i = c10.a();
        a.a c11 = a.c();
        c11.c(6);
        c11.b("An internal error occurred.");
        j = c11.a();
        a.a c12 = a.c();
        c12.c(5);
        c12.b("SKU can't be null.");
        k = c12.a();
        a.a c13 = a.c();
        c13.c(0);
        l = c13.a();
        a.a c14 = a.c();
        c14.c(-1);
        c14.b("Service connection is disconnected.");
        m = c14.a();
        a.a c15 = a.c();
        c15.c(2);
        c15.b("Timeout communicating with service.");
        n = c15.a();
        a.a c16 = a.c();
        c16.c(-2);
        c16.b("Client does not support subscriptions.");
        o = c16.a();
        a.a c17 = a.c();
        c17.c(-2);
        c17.b("Client does not support subscriptions update.");
        p = c17.a();
        a.a c18 = a.c();
        c18.c(-2);
        c18.b("Client does not support get purchase history.");
        q = c18.a();
        a.a c19 = a.c();
        c19.c(-2);
        c19.b("Client does not support price change confirmation.");
        r = c19.a();
        a.a c20 = a.c();
        c20.c(-2);
        c20.b("Play Store version installed does not support cross selling products.");
        s = c20.a();
        a.a c21 = a.c();
        c21.c(-2);
        c21.b("Client does not support multi-item purchases.");
        t = c21.a();
        a.a c22 = a.c();
        c22.c(-2);
        c22.b("Client does not support offer_id_token.");
        u = c22.a();
        a.a c23 = a.c();
        c23.c(-2);
        c23.b("Client does not support ProductDetails.");
        v = c23.a();
        a.a c24 = a.c();
        c24.c(-2);
        c24.b("Client does not support in-app messages.");
        w = c24.a();
        a.a c25 = a.c();
        c25.c(-2);
        c25.b("Client does not support user choice billing.");
        x = c25.a();
        a.a c26 = a.c();
        c26.c(-2);
        c26.b("Play Store version installed does not support external offer.");
        y = c26.a();
        a.a c27 = a.c();
        c27.c(5);
        c27.b("Unknown feature");
        z = c27.a();
        a.a c28 = a.c();
        c28.c(-2);
        c28.b("Play Store version installed does not support get billing config.");
        A = c28.a();
        a.a c29 = a.c();
        c29.c(-2);
        c29.b("Query product details with serialized docid is not supported.");
        B = c29.a();
        a.a c30 = a.c();
        c30.c(4);
        c30.b("Item is unavailable for purchase.");
        C = c30.a();
        a.a c31 = a.c();
        c31.c(-2);
        c31.b("Query product details with developer specified account is not supported.");
        D = c31.a();
        a.a c32 = a.c();
        c32.c(-2);
        c32.b("Play Store version installed does not support alternative billing only.");
        E = c32.a();
        a.a c33 = a.c();
        c33.c(5);
        c33.b("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        F = c33.a();
    }

    public static a a(int i2, String str) {
        a.a c2 = a.c();
        c2.c(i2);
        c2.b(str);
        return c2.a();
    }
}
